### ISSUE TITLE
AWS IAM Check 1.18 Ensure IAM Master and IAM Manager roles are active  had been deleted

### ISSUE THREAD

**Issue by omerfsen** [nozaq/terraform-aws-secure-baseline#109]
I see you have also implemented 

1.18 - Ensure IAM Master and IAM Manager roles are active (deleted)
on https://raw.githubusercontent.com/nozaq/terraform-aws-secure-baseline/master/modules/iam-baseline/main.tf

This  requirement was deleted with -ticket 6371  ( https://workbench.cisecurity.org/tickets/6371 can only be seen with creating free account)

while it does not hurt but it can be deleted.

**Comment by nozaq** [comment]
@omerfsen thanks for the update and sorry for the delay! creating an IAM role is now optional since v0.19.0, I'll also consider changing the default behavior not to create this role later :+1:

**Comment by nozaq** [comment]
implemented in #134!
