### ISSUE TITLE
New SecurityHub standards support

### ISSUE THREAD

**Issue by lukaspour** [nozaq/terraform-aws-secure-baseline#112]
There are two new standards in SecurityHub - "PCI DSS" and "AWS Foundational Security Best Practices". It would be nice to add their support to this module. 

It would also be good to allow each standard to be enabled / disabled independently using module variables.

**Comment by lukaspour** [comment]
fix available here #113

**Comment by nozaq** [comment]
@lukaspour sorry for the delay, #113 just merged and published in 0.19.0 :+1:
