### ISSUE TITLE
Suggestions: Make all iam roles/policies to be optional

### ISSUE THREAD

**Issue by igordcsouza** [nozaq/terraform-aws-secure-baseline#114]
I was trying it out and a few things on our account are already managed by other modules, so it will be great to not have more roles and policies that we already have. 
For that, I've put a few more variables on the iam-baseline sub-module so we could disable the roles/policies creation.
This doesn't affect the people that are already using the module since the default value is set to create all roles but could help others that will try to use it on an account already in use.

I'll open a PR with the changes to review!

Thanks for the work on that, it's a pretty good module and will help us a lot!

**Comment by nozaq** [comment]
@igordcsouza sorry for the delay, #115 has been merged and published in v0.19.0!
