### ISSUE TITLE
terraform-provider-aws v3.0.0 breaks aws_cloudwatch_log_group output

### ISSUE THREAD

**Issue by ryzr** [nozaq/terraform-aws-secure-baseline#118]
Just thought I'd open an issue, as I'm not sure the best way to implement a fix, while remaining backwards compatible with terraform-provider-aws 2.x.

Please see:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#removal-of-arn-wildcard-suffix

Ultimately, the fix is to update this line:
https://github.com/nozaq/terraform-aws-secure-baseline/blob/master/modules/cloudtrail-baseline/main.tf#L243

To:
```hcl
cloud_watch_logs_group_arn = "${aws_cloudwatch_log_group.cloudtrail_events[0].arn}:*"
```

If you wish to remain compatible with 2.x, I guess you could do something like
```hcl
cloud_watch_logs_group_arn = replace("${aws_cloudwatch_log_group.cloudtrail_events[0].arn}:*", ":*:*", ":*")
```

**Comment by nozaq** [comment]
@ryzr 
Thank you for this update! Just confirmed the behavior on my side too.
I'll publish version 0.19.0 which is the last version compatible with aws provider 2.x, then fix this issue in 0.20.0.
