### ISSUE TITLE
Allow for non-creation of IAM user-roles

### ISSUE THREAD

**Issue by jayzalowitz** [nozaq/terraform-aws-secure-baseline#125]
The system I am working on does not need IAM policies as its managed in other ways, is there any way you would consider adding a variable to disable the non-service IAM at top module level?

**Comment by nozaq** [comment]
Role creation was made optional in the below PR, and this change was published as v0.21.0!
https://github.com/nozaq/terraform-aws-secure-baseline/pull/127
