### ISSUE TITLE
Allow changing default VPC by passing a VPC arn/id/name

### ISSUE THREAD

**Issue by tovbinm** [nozaq/terraform-aws-secure-baseline#142]

**Comment by nozaq** [comment]
The purpose of having resources regarding default VPCs is that they have insecure rules by default and AWS treats them quite differently compared to other manually created ones.
I recommend to create non-default VPCs by using other modules or templates, which supposed to be more customizable.
I've published [a module](https://github.com/nozaq/terraform-aws-secure-vpc), but there should be other candidates as well.

**Comment by tovbinm** [comment]
Yes, we actually have the non default VPC as well. This is the recomended way, not only security wise, but also when using Terraform.

**Comment by tovbinm** [comment]
We are using this module for creating VPCs - https://github.com/terraform-aws-modules/terraform-aws-vpc
