### ISSUE TITLE
Allow sending VPC flow logs directly S3 instead of CloudWatch

### ISSUE THREAD

**Issue by tovbinm** [nozaq/terraform-aws-secure-baseline#144]
This would be great for cost considerations. See - https://aws.amazon.com/cloudwatch/pricing/

Using S3 is twice as cheap.

**Comment by jmcorallo** [comment]
Hi @nozaq, is this in progress? Else I can handle it since I could also use this feature

**Comment by nozaq** [comment]
@jmcorallo Not actually. I'd be happy to review if you could send a PR 👍🏼

**Comment by jmcorallo** [comment]
@nozaq see https://github.com/nozaq/terraform-aws-secure-baseline/pull/151
