### ISSUE TITLE
Inconsistent file structure and naming

### ISSUE THREAD

**Issue by jmcorallo** [nozaq/terraform-aws-secure-baseline#149]
Maybe this issue is a bit nit-picky. The [standard module structure](https://www.terraform.io/docs/modules/index.html#standard-module-structure) states:
`main.tf, variables.tf, outputs.tf. These are the recommended filenames for a minimal module, even if they're empty. main.tf should be the primary entrypoint. For a simple module, this may be where all the resources are created. For a complex module, resource creation may be split into multiple files but any nested module calls should be in the main file.`

This repo is calling some modules in the main.tf file, whereas others have specific .tf files (which are not consistently named, ie. `analyzer.tf` vs `config_baselines.tf`). IMO it should either have everything in main, or everything in resource-specific files.

**Comment by nozaq** [comment]
@jmcorallo Thanks for your suggestion 👍🏼 

> IMO it should either have everything in main, or everything in resource-specific files.

I'm not sure if resource creations should be avoided in `main.tf` file when a module have other tf files 🤔 
What I understand from standard module structure is as follows:
- A module should have `main.tf` file even if it's empty.
- A module could have additional tf files if it's too complex to put everything in one `main.tf` file.
- Resource creations could happen in `main.if` or any other tf files(not in variables.tf or outputs.tf, of course).
- Nested module calls should be put in `main.tf` file, not other tf files.

Regarding file namings, nested modules have been added from time to time so they could have inconsistent file names. I'm open to discuss if you have any suggestions!

**Comment by nozaq** [comment]
I'll close this issue for now as things have been slightly fixed in #154 and #155 .
Please re-open it or create another issue if you have any additional suggestion, thanks!
