### ISSUE TITLE
disable/enable individual alarms

### ISSUE THREAD

**Issue by dad264** [nozaq/terraform-aws-secure-baseline#162]
I'd like to be able to disable/enable individual alarms in [alarm-baseline](https://github.com/nozaq/terraform-aws-secure-baseline/tree/master/modules/alarm-baseline)

In our accounts, all of the S3 logs go to cloudtrail so we are getting alarmed constantly on simple 401s for s3 backed websites.

I'm willing to send in the PR if this sounds reasonable.

**Comment by nozaq** [comment]
@dad264 
Sorry, it's been a month to repond here. Yes, I understand a part of alarms needs to be turned off for some cases.
Will be open to review the PR if available :)
