### ISSUE TITLE
SNS topics should be encrypted at-rest using AWS KMS [SNS.1]

### ISSUE THREAD

**Issue by willfarrell** [nozaq/terraform-aws-secure-baseline#163]
- [ ] CISAlarm https://github.com/nozaq/terraform-aws-secure-baseline/blob/master/modules/alarm-baseline/main.tf#L5
- [ ] ConfigChanges https://github.com/nozaq/terraform-aws-secure-baseline/blob/master/modules/config-baseline/main.tf#L5

Should there be a secondary KMS key for these other SNS? Reuse the cloudtrail KMS key? Move the KMS from cloudtrail up, then share among all? Pass in a KMS key for these?

**Comment by nozaq** [comment]
@willfarrell Thanks for the suggestion!
Looking at "Key Creation and Management" section in [AWS Key Management Service Best Practices](https://d1.awsstatic.com/whitepapers/aws-kms-best-practices.pdf), I understand CMKs don't need to be created for each AWS service, but it should created for each data classification type / security requirements.

I guess using one CMK for CloudTrail and  SNS topics is enough for most cases, but allowing to override each CMK id is also useful for some users.

**Comment by kut** [comment]
This would make sense for our use case (currently we have to override the SNS topics to encrypt them for AWS KMS [SNS.1])
