### ISSUE TITLE
terraforming organization fails for access analyzer and cloudtrail

### ISSUE THREAD

**Issue by derylseale** [nozaq/terraform-aws-secure-baseline#166]
There seems to be an issue with missing service roles when terraforming an organization master account. I ran into the following two errors:
````
Error: Error creating CloudTrail: CloudTrailAccessNotEnabledException: The request could not be processed because your organization hasn’t enabled CloudTrail service access. Enable service access for CloudTrail, and then try again. You are signed in with the following AWS account ID: 99999999999
````
and 
````
error creating Access Analyzer Analyzer (default-analyer): ValidationException: Service not enabled for AWS Organizations
````
I manually created and then destroyed a multi-account trail and and organization access analyzer, and re-ran terraform successfully. It looks like the two service roles that AWS creates automatically are AWSServiceRoleForAccessAnalyzer and AWSServiceRoleForCloudTrail. I don't know why they're not created automatically during the terraform run, but their absence causes a failure.

**Comment by nozaq** [comment]
@derylseale Thank you for reporting the issue!

I found that terraform-provider-aws provides [a resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_service_linked_role) to manage service linked roles. But on the other hand, AWS claims that these roles will be automatically created even through API calls.

I'm planning to invetigate more with the newly created AWS account soon.

**Comment by patheard** [comment]
I had this issue because when I'd created my organization, I hadn't added a service access principal for CloudTrail.  This fixed it for me and caused Amazon to create the required roles:

```hcl
resource "aws_organizations_organization" "root" {
  aws_service_access_principals = [
    "cloudtrail.amazonaws.com"
  ]
  # other properties
}
