### ISSUE TITLE
S3 Block Public Access settings for this account

### ISSUE THREAD

**Issue by willfarrell** [nozaq/terraform-aws-secure-baseline#176]
Add config to block public access to s3 (global)
- PCI.S3.6
- AWS.S3.1

```terraform
resource "aws_s3_account_public_access_block" "main" {
  block_public_acls   = true
  block_public_policy = true
  ignore_public_acls = true
  restrict_public_buckets = true
}
```

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_account_public_access_block

**Comment by DupeDupeDupe** [comment]
It looks like this is already set: 

https://github.com/nozaq/terraform-aws-secure-baseline/blob/master/modules/secure-bucket/main.tf#L119

**Comment by willfarrell** [comment]
Awesome, must be a new option I need to enable.

**Comment by nozaq** [comment]
While the log bucket this module creates already blocks all public accesses, enabling the account-level protection could be better.
Thanks for the suggestion!
