### ISSUE TITLE
duplicate guard duty detector created by member accounts

### ISSUE THREAD

**Issue by drewmullen** [nozaq/terraform-aws-secure-baseline#199]
i just started using this so apologies if im missing something. looks like member accounts try to create a guard duty detector when one has already been created by the organization after it joins the org. 

```
│ Error: Creating GuardDuty Detector failed: BadRequestException: The request is rejected because a detector already exists for the current account.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "106157e8-68c3-41f8-b829-45c885d5cf03"
│   },
│   Message_: "The request is rejected because a detector already exists for the current account.",
│   Type: "InvalidInputException"
│ }
│
│   with module.secure_baseline.module.guardduty_baseline_us-east-1.aws_guardduty_detector.default[0],
│   on .terraform/modules/secure_baseline/modules/guardduty-baseline/main.tf line 5, in resource "aws_guardduty_detector" "default":
│    5: resource "aws_guardduty_detector" "default" {
│
```

this should fix it. ill open a PR shortly that fixes this

**Comment by drewmullen** [comment]
https://github.com/nozaq/terraform-aws-secure-baseline/pull/200#issuecomment-880881996

see comment

**Comment by drewmullen** [comment]
I'm still seeing issues with this. Here is what i think is happening:
1. account is created using aws organizations
2. account is added as a `member_account` in the `master` module invocation
3. in the background, guardduty creates the detector for accounts it manages
4. `member` module invocation fails because it tries to create the detector

also just to note, if you login to the new account during step 3, you may not see the detector for ~10m

im curious why no one else has run into this - any thoughts @nozaq ?

**Comment by nozaq** [comment]
@drewmullen Hi, thanks for reporting it and sending the PR! 

According to [the AWS provider doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_member), `aws_guardduty_detector` resource is supposed to be created for both master and member accounts. So I'm afraid skipping the creation of `aws_guardduty_detector` for member accounts as suggested in #228 wouldn't be a right fix.

This module is intended to be called as following.

- The master account should call this module with `member_accounts` argument set.
- Member accounts should call this module with `master_account_id` argument set.

Then `aws_guardduty_detector` will be created in each account and `aws_guardduty_member` resource will only be created in the master account.

Could you give an example how you call this module in your master/member accounts?

One possible cause is that your account have already enabled GuardDuty in the past without this module, in that case [importing `aws_guardduty_detector` resources](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_member#import) would solve the issue.

**Comment by drewmullen** [comment]
howdy - yeah so thats exactly how im using the module (master/member) mentioned above. also the PR i provided is working perfectly in my situation. when i first reported this issue i thought maybe it was something in my environment because i was experimenting by creating/destroying the securebaseline setup. however, now im certain this is the issue because im creating new accounts 

master HCL:
```module "secure_baseline" {
  source  = "nozaq/secure-baseline/aws"
  version = "0.29.2"

  account_type                         = "master"
  member_accounts                      = local.member_accounts
  audit_log_bucket_name                = local.audit_bucket_name
  aws_account_id                       = data.aws_caller_identity.current.account_id
  region                               = data.aws_region.current.name
  support_iam_role_principal_arns      = [aws_iam_user.admin.arn]
  create_support_role                  = true
  guardduty_disable_email_notification = true
  target_regions                       = var.target_regions

  providers = {
<redacted for clarity>
  }
}
```

member:
```
module "secure_baseline-dev" {
  source = "../../../drmullen/git/terraform-aws-secure-baseline"
  version = "0.29.2"

  account_type                         = "member"
  master_account_id                    = data.aws_organizations_organization.org.master_account_id
  audit_log_bucket_name                = data.terraform_remote_state.master-baseline.outputs.audit_bucket_name
  use_external_audit_log_bucket        = true
  aws_account_id                       = data.aws_caller_identity.current.account_id
  region                               = var.region
  support_iam_role_principal_arns      = [aws_iam_user.admin_dev.arn]

  target_regions                       = var.target_regions

  providers = {
<redacted for clarity>
  }
}
```

**Comment by mgrotheer** [comment]
I'm not sure if this question is related and/or should be put in a different thread, but how is authentication working into all of the member accounts here? From how I understand it, we can pass in a list of account ids/emails but we need a way of passing in aws profiles for authentication into each account. Is that correct?

**Comment by drewmullen** [comment]
it took me a while to figure this out but this was caused by an internal processes related to creating orgs.
