### ISSUE TITLE
Use KMS multi-region keys for the default key

### ISSUE THREAD

**Issue by nozaq** [nozaq/terraform-aws-secure-baseline#218]
Use [KMS Multi-Region Keys](https://aws.amazon.com/about-aws/whats-new/2021/06/kms-multi-region-keys/) to centralize the CMK creation, which is currently distributed among regions.

- Replace single-region keys with the multi-region key.
- Use the multi-region key for..
    - CloudTrail encryption
    - SNS topic encryption
- Optionally supporting single-region keys could be helpful, but the design depends on the upstream implementation. 

**Current status**
Waiting for the multi-region keys to be supported in terraform-aws-provider(See [this issue](https://github.com/hashicorp/terraform-provider-aws/issues/19896)).

Ref: #182 #216

**Comment by willfarrell** [comment]
Now supported in terraform
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_replica_key

**Comment by nozaq** [comment]
AWS suggests to use multi-region keys only if there is clear benefit since they introduce additional security concerns([ref](https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html#mrk-when-to-use)). 
Need to investigate more before deciding to use multi-region keys instead of having a single-region key for each region.

**Comment by nozaq** [comment]
After considering tradeoffs, I didn't find clear benefit over complications.
Closing it for now.
