### ISSUE TITLE
Use different region for external audit s3 bucket

### ISSUE THREAD

**Issue by negacion** [nozaq/terraform-aws-secure-baseline#225]
Hi.

Let's say all my resources are deployed in a defined region (e.g. A) , but I want to use an external audit log bucket and this bucket is deployed on a different region (e.g. B) from all my resources. 

If I understand it correctly, your module does not seem to allow such a thing. Or is there something I missed ? 

Thanks for your help

**Comment by nozaq** [comment]
Your understanding is correct. Currently the bucket is required to be accesible from the default aws provider, i.e. needs to be in the main region.
This is due to the limitaion of 'aws_s3_bucket' datasource.
