### ISSUE TITLE
Error: Unsupported block type "datasources"

### ISSUE THREAD

**Issue by php-workx** [nozaq/terraform-aws-secure-baseline#226]
Hey! 

Thanks for the great work y'all have put together here! I ran into this error today ... 

`Error: Unsupported block type
│ 
│   on .terraform/modules/secure_baseline/modules/guardduty-baseline/main.tf line 12, in resource "aws_guardduty_detector" "default":
│   12:   dynamic "datasources" {
│ 
│ Blocks of type "datasources" are not expected here.`

https://github.com/nozaq/terraform-aws-secure-baseline/blame/main/modules/guardduty-baseline/main.tf#L12

... and thought I'll report it here. The error is caused by the minimum AWS provider version `3.39.0` which does not allow dynamic datasources there. After an upgrade to the latest version of the AWS provider it works like charm. So it seems like we should update the minimum version here: https://github.com/nozaq/terraform-aws-secure-baseline/blob/main/main.tf#L7

Thanks so much!
Ronny

**Comment by nozaq** [comment]
@php-workx 
Right, it seems that `datasources` argument was introduced in [v3.50.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3500-july-15-2021).
I'll update the minimum version shortly, thanks for reporting!
