### ISSUE TITLE
Update Security Hub to support cross-Region aggregation of findings

### ISSUE THREAD

**Issue by willfarrell** [nozaq/terraform-aws-secure-baseline#231]
https://aws.amazon.com/about-aws/whats-new/2021/10/aws-security-hub-cross-region-security-posture/

**Comment by nozaq** [comment]
Note: It seems finding_aggregator resource has not been not added in [terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws) yet. Let's come back to this issue when it's ready 👍🏼

**Comment by nozaq** [comment]
`aws_securityhub_finding_aggregator` is now implemented.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_finding_aggregator
