### ISSUE TITLE
Support to opt out of cloudtrail baseline for master or individual account

### ISSUE THREAD

**Issue by RohanArya4894** [nozaq/terraform-aws-secure-baseline#235]
Hi Team, It seems like a good option if we could choose to not enable cloudtrail baseline for master or individual account as well and also any other baseline module which does not have a boolean flag to enable/disable it.

**Comment by nozaq** [comment]
@RohanArya4894 Hi, I'm working on #232 to refactor submodule switching. Will add look into this after that!

In the mean time, you can directly call [submodules](https://github.com/nozaq/terraform-aws-secure-baseline#submodules) in your project. Thanks!
