### ISSUE TITLE
member accounts do not have access to audit log bucket

### ISSUE THREAD

**Issue by derylseale** [nozaq/terraform-aws-secure-baseline#260]
## Describe the bug
Per the examples, member accounts are set up to reference the audit log bucket created for the master account. Subsequent terraform runs on these account work fine, but they trigger an Access Denied event in AWS for the audit log bucket. We use assumed roles for member account access, per AWS best practice recommendations, but those roles are not part of the audit log bucket access policy. Hence the access denied error.

This might be my misunderstanding, or it might be out of scope for this module. Is there a recommended JSON bucket policy to include in the master account configuration to allow access for member account roles?

## Versions

- Terraform: v1.1.5
- Provider: v3.73.0
- Module: 0.34.0

## Reproduction

Set up master and member accounts per the examples in this repository, and then run terraform plan on any member account.

## Expected behavior

No AWS Access Denied events when running terraform.

## Actual behavior

Terraform runs without error but AWS triggers an Access Denied event, which in turn puts the Unauthorized API Calls alert into the alarm state.

**Comment by nozaq** [comment]
@derylseale Sorry for the late reply 🙏🏼 
I guess you need to set `var.member_accounts` for the master account module, which defaults to `[]`.

**Comment by derylseale** [comment]
I have set the `var.member_accounts` variable correctly, and I can see that the bucket policy allows access for the root users for those members. The issue is that we run terraform with a non-root user that assumes a privileged role for the member account, and that role does not have access to the bucket.

I can see two ways to remedy this:

1. Amend the bucket policy to allow access for the privileged roles. **Will `audit_log_bucket_custom_policy_json` append to the generated bucket policy or overwrite it?**
2. Generate a new role to allow access to the bucket, and attach it to the user who executes terraform. 

Is either option preferable? Or is there another option that is better than these two?

**Comment by derylseale** [comment]
Although upon further reflection, I am not sure option 2 would work. We assume a privileged role for the member account when executing terraform, and even if the user also had a role for accessing the bucket in the master account, I don't think that would be in play (i.e. the assumed role is the only one that is evaluated). I'll test it out, but I don't think it will work.

**Comment by nozaq** [comment]
@derylseale Thanks for the additional explanation! I understand that you'd like to allow additional roles to access the audit log bucket, which was automatically created by `secure-baseline` module.

From the options you mentioned, I'd recommend Option 1. `var.audit_log_bucket_custom_policy_json` will be merged into the policy the module creates. Implementation-wise, it is passed as `override_policy_documents` argument to `data.aws_iam_policy_document.audit_log` ([here](https://github.com/nozaq/terraform-aws-secure-baseline/blob/main/bucket.tf#L243) is the actual code, just for reference). [AWS provider document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document) describes how merging multiple policy documents works.

Another option would be to use `var.use_external_audit_log_bucket` which tells the module not to create the audit log bucket. In this way, you can create the bucket however you want. [`external_bucket` example](https://github.com/nozaq/terraform-aws-secure-baseline/tree/main/examples/external-bucket) describes this pattern.

Please let me know if you have any questions or concerns.

**Comment by derylseale** [comment]
I was able to get this working using your suggestion of the `audit_log_bucket_custom_policy_json` attribute. It was a little tricky, so I thought I'd outline the steps I took below in case it helps someone in the future.

1. I added a `cross_account_role` attribute to the `member-accounts` structure. When using STS to assume a role, you have to use the **unique role ID** in the policy statement, because the token part is always different. (See step 2 below)
```
member-accounts = [
    {
      account_id         = "1234567890"
      email              = "email@your.co"
      cross_account_role = "AROABLAHBLAHBLAH"
    }
]
```
2. I then created a new `aws_iam_policy_document` data element for the new statement to merge into the bucket policy. Note that you must use a condition statement to restrict the authorized principals, because that is the only place that allows the wildcard necessary to reference the ever-changing STS token. The only S3 operation that was failing was `GetBucketWebsite` but there might be more that I have not yet encountered.
```
data "aws_iam_policy_document" "audit-bucket" {

  statement {
    sid    = "Allow Cross Account Role Access"
    effect = "Allow"
    principals {
      identifiers = ["*"]
      type        = "*"
    }
    actions   = ["s3:GetBucketWebsite"]
    resources = ["arn:aws:s3:::${local.audit_log_bucket_name}"]
    condition {
      test     = "StringLike"
      values   = [for m in var.member-accounts : "${m.cross_account_role}:*"]
      variable = "aws:userId"
    }
  }

}
```
3. Finally, I referenced the data element from step 2 in the `secure_baseline` module.
```
audit_log_bucket_custom_policy_json = data.aws_iam_policy_document.audit-bucket.json
```
This seems to have eliminated the spurious Access Denied errors I encountered. Any additional access necessary can always be added to the statement above. Thanks for your suggestion, glad to have this great module working perfectly for me now!

**Comment by nozaq** [comment]
@derylseale Great to hear that it's working, and thanks for sharing the way you resolved it! 👍🏼
