### ISSUE TITLE
Error: Error creating S3 bucket: BucketAlreadyExists

### ISSUE THREAD

**Issue by harbinc** [nozaq/terraform-aws-secure-baseline#274]
I am seeing the following error. How can I change the bucket name? I have multiple shared account and this seems to be an issue.

│ Error: Error creating S3 bucket: BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name
and try again.
│       status code: 409, request id: T4KJNCR0X21GNWJN, host id: xXxyej9r7aEwqjbR+yHlbIODeDRUKp+BQfxD8oscN/vm7ovVQqARKeulLLttrSRKc3CNtvSwjWU=
│
│   with module.secure-baseline.module.audit_log_bucket.aws_s3_bucket.access_log[0],
│   on .terraform\modules\secure-baseline\modules\secure-bucket\main.tf line 23, in resource "aws_s3_bucket" "access_log":
│   23: resource "aws_s3_bucket" "access_log" {

Here is my configuration.

terraform {
  required_version = ">= 0.15"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.50.0"
    }
  }
}

module "secure-baseline" {
  source  = "nozaq/secure-baseline/aws"
  version = "0.30.0"

│

**Comment by nozaq** [comment]
@harbinc Hi, thanks for reporting the issue! 

Did you pass `audit_log_bucket_name` argument to the module? 
It would be helpful if you could show which arguments are passed to the module.

**Comment by harbinc** [comment]
I did not pass the bucket name argument. Here is my terraform. I am new to terraform so please forgive any issues.

terraform {
  required_version = ">= 0.15"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.50.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

data "aws_caller_identity" "current" {
}

resource "aws_iam_user" "admin" {
  name = "admin"
}

#Secure AWS account CIS Amazon Web Services Foundations v1.4.0 and AWS Foundational Security Best Practices v1.0.0.
#Identity and Access Management Logging & Monitoring Networking & Computing
module "secure-baseline" {
  source  = "nozaq/secure-baseline/aws"
  version = "0.30.0"

  audit_log_bucket_name           = var.audit_s3_bucket_name
  aws_account_id                  = data.aws_caller_identity.current.account_id
  region                          = var.region
  support_iam_role_principal_arns = [aws_iam_user.admin.arn]
  
  #IAM PASSWORD POLICY SETTINGS
  allow_users_to_change_password = true
  max_password_age               = 90
  minimum_password_length        = 14
  password_reuse_prevention      = 24
  require_lowercase_characters   = true
  require_numbers                = true
  require_symbols                = true
  require_uppercase_characters   = true

  # Setting it to true means all audit logs are automatically deleted
  #   when you run `terraform destroy`.
  # Note that it might be inappropriate for highly secured environment.
  audit_log_bucket_force_destroy = true

  providers = {
    aws                = aws
    aws.ap-northeast-1 = aws.ap-northeast-1
    aws.ap-northeast-2 = aws.ap-northeast-2
    aws.ap-northeast-3 = aws.ap-northeast-3
    aws.ap-south-1     = aws.ap-south-1
    aws.ap-southeast-1 = aws.ap-southeast-1
    aws.ap-southeast-2 = aws.ap-southeast-2
    aws.ca-central-1   = aws.ca-central-1
    aws.eu-central-1   = aws.eu-central-1
    aws.eu-north-1     = aws.eu-north-1
    aws.eu-west-1      = aws.eu-west-1
    aws.eu-west-2      = aws.eu-west-2
    aws.eu-west-3      = aws.eu-west-3
    aws.sa-east-1      = aws.sa-east-1
    aws.us-east-1      = aws.us-east-1
    aws.us-east-2      = aws.us-east-2
    aws.us-west-1      = aws.us-west-1
    aws.us-west-2      = aws.us-west-2
  }

}

**Comment by nozaq** [comment]
@harbinc Thank you! 

This module tries to create two S3 bucket, one for storing CloudTrail records(trail bucket) and another for storing access logs for it(log bucket).
The name of these buckets decided based on `audit_log_bucket_name` argument, which you set via `var.audit_s3_bucket_name` variable. The name of the trail bucket would be the value of `audit_s3_bucket_name` itself, and the name of the log bucket would be `audit_s3_bucket_name` suffixed by `-access-log`, i.e. "${audit_s3_bucket_name}-access-logs".

According to the error message you reported, it seems the bucket name "${audit_s3_bucket_name}-access-logs" already exists. You can avoid this error by changing `var.audit_s3_bucket_name` to other names. Note that it also changes your trail bucket name as well.

> I am new to terraform so please forgive any issues.

No worries, everyone was once a beginner 😄 

Please let me know if you have any questions or comments.

**Comment by harbinc** [comment]
Thanks! I did run this against another account and that was the issue.

**Comment by nozaq** [comment]
@harbinc Glad to hear. Closing this issue for now then.
