### ISSUE TITLE
Upgrade to 1.0 guide should import access_log bucket resource, too

### ISSUE THREAD

**Issue by mpalmer** [nozaq/terraform-aws-secure-baseline#280]
## Describe the bug

Attempting to upgrade to 1.0.1 from 0.29.2, and having (I *think*) correctly followed the [upgrade guide](https://github.com/nozaq/terraform-aws-secure-baseline/blob/main/docs/upgrade-1.0.md), I get the following error:

```
module.secure_baseline.module.audit_log_bucket[0].aws_s3_bucket.access_log: Creating...
│ Error: Error creating S3 bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
│       status code: 409, request id: <thing>, host id: <thing>
│
│   with module.secure_baseline.module.audit_log_bucket[0].aws_s3_bucket.access_log,
│   on .terraform/modules/secure_baseline/modules/secure-bucket/main.tf line 21, in resource "aws_s3_bucket" "access_log":
│   21: resource "aws_s3_bucket" "access_log" {
│
```

## Versions

- Terraform: 1.1.7
- Provider: 4.6.0
- Module: 1.0.1

## Reproduction

Attempt to upgrade.

## Expected behavior

Error does not appear.

## Actual behavior

Error appears.

## Additional context

I was able to correct the error by running the following command:

```
terraform import "$MODULE_PATH.module.audit_log_bucket[0].aws_s3_bucket.access_log" "$ACCESS_LOG_BUCKET"
```

**Comment by nozaq** [comment]
@mpalmer Sorry for being late here, but the document was fixed as in #289.
Thank you for the feedback!
