### ISSUE TITLE
Make Audit Bucket Glacier Lifecycle Configuration Optional

### ISSUE THREAD

**Issue by derylseale** [nozaq/terraform-aws-secure-baseline#291]
## Is your feature request related to a problem? Please describe.

Glacier requests can add up to a significant expense, making this lifecycle policy not worth the cost for environments with more modest security requirements.

## Describe the solution you'd like

Allow the glacier lifecycle configuration to be optional, either through a new parameter or by setting the transition days to 0 (even though this is a valid lifecycle configuration option).

## Describe alternatives you've considered

Setting up an external audit bucket with the appropriate lifecycle configuration, though this is a lot of overkill and boilerplate code to address such a small part of the configuration.

**Comment by nozaq** [comment]
Thank you for your suggestion!

I've checked around the official AWS document and found that transitioning small objects is not recommended. #293 will make these rules optional as well as disabling them by default.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-transition-general-considerations.html

**Comment by nozaq** [comment]
Released in v2.0.0

**Comment by derylseale** [comment]
Thanks for the quick turnaround. I was also unaware of this, until I saw our AWS bill. Always learning.
