### ISSUE TITLE
Region Issue

### ISSUE THREAD

**Issue by LittleBoyTimmy** [nozaq/terraform-aws-secure-baseline#30]
I have been trying to integrate the module within my project and I keep running into a problem with the regions. I am getting an error for each of the different regions flow logs that read: "aws_flow_log.default_vpc_flow_logs: Error creating Flow Log for (vpc-e5602182), error: InvalidParameter: LogDestination must be in the same region as the API caller."

Any help would be very appreciated!

**Comment by nozaq** [comment]
@LittleBoyTimmy Thanks for reporting the issue! :) 
The problem is that AWS now requires a CloudWatch Logs group to exist in the same region as the VPC itself. I've fixed it in #29 and released as version 0.7.0. 

Could you use 0.7.0 and try again? 

Please let me know if the error still occur.

**Comment by LittleBoyTimmy** [comment]
Looks like that fixed it! Thank you for the response!
