### ISSUE TITLE
Upgrade Security Hub CIS to v1.4.0

### ISSUE THREAD

**Issue by willfarrell** [nozaq/terraform-aws-secure-baseline#305]
## Is your feature request related to a problem? Please describe.

Use latest version of CIS AWS Foundations Benchmark

## Describe the solution you'd like

Upgrade CIS AWS Foundations Benchmark v1.2.0 to CIS AWS Foundations Benchmark v1.4.0

## Additional context

https://aws.amazon.com/about-aws/whats-new/2022/11/security-hub-center-internet-securitys-cis-foundations-benchmark-version-1-4-0/

**Comment by nozaq** [comment]
Thanks for reporting, v2.1.0 uses CIS benchmark v1.4.0 👍🏼
