### ISSUE TITLE
Terraform 0.12

### ISSUE THREAD

**Issue by digitalkaoz** [nozaq/terraform-aws-secure-baseline#36]
The new stable version is released and a few things need to be upgraded!

**Comment by ankitsrao** [comment]
Hi digitalkaoz,

Can you please provide some insights on how to setup the configuration.? TIA

**Comment by digitalkaoz** [comment]
https://www.terraform.io/upgrade-guides/0-12.html

**Comment by nozaq** [comment]
Thanks for the report!
Just upgraded in #38, please let me know if you guys find any issues :)

**Comment by digitalkaoz** [comment]
Merci Bien!

nozaq <notifications@github.com> schrieb am Fr., 24. Mai 2019, 13:57:
