### ISSUE TITLE
Question about Cloudwatch Alarm

### ISSUE THREAD

**Issue by JoostSaanen** [nozaq/terraform-aws-secure-baseline#39]
Thx for this great project.
One question regarding Cloudwatch alarms. For example:  `S3BucketPolicyChanges`.

What is the best and fastest way to see WHY an alarm was triggered? In the cloudwatch alarm history I only see the post to the sns topic, but there is no log or something with Cloudtrail in it. Any tips?
Keep up the good work!

**Comment by nozaq** [comment]
@JoostSaanen 
Each alarm has a corresponding metric filter pattern associated, [this pattern](https://github.com/nozaq/terraform-aws-secure-baseline/blob/master/modules/alarm-baseline/main.tf#L204) for S3BucketPolicyChanges for example.
Relevant CloudTrail logs can be retrieved by querying the above filter pattern to the CloudWatch Log Group. There are two ways to get this done from  AWS Mamagement Console.
1. Open CloudWatch Metrics then use "View logs" to apply the corresponding filter pattern to CloudWatch Logs. *To get from metrics to logs* section in [the AWS doc](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SearchDataFilterPattern.html#pivot-metrics-logs) describes for more detail.
2. Open CloudWatch Log Group then directly type the filter pattern. See [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SearchDataFilterPattern.html#search-log-entries).

Hope it would help, please let me know if you have other questions! :)

**Comment by JoostSaanen** [comment]
@nozaq Thanks for your time for answering my question! 

I was thinking of a way to integrate the relevant Cloudtrail logs into the message of the post to the topic. I have an integration with SNS and Slack so I am able to see all alarms in Slack. How it works now,  it's a bit of a hassle to quickly find the cause of an cloudwatch alarm. Would be cool if the cloudtrail info is already included  in the Slack message. Any thoughts on that?

**Comment by nozaq** [comment]
@JoostSaanen 
Ah, now I got your point! I agree it would be beneficial if we could include actual log records in alarm messages :+1: 

CloudWatch Alarms itself does not send such information when it publishes a message to the SNS topic, so we need some intermediate lambda function to collect log records before sending messages.
It seems that [this repo](https://github.com/awslabs/cloudwatch-logs-customize-alarms)  is very much relevant to this idea.
 
It is possible to implement the above function in this module though, some people may not want to expose actual log contents in alarm messages. 
Given that, I'm wondering if this could be provided as a separated terraform module... :thinking:
