### ISSUE TITLE
Error deleting S3 Bucket

### ISSUE THREAD

**Issue by kylelundstedt** [nozaq/terraform-aws-secure-baseline#48]
When running `terraform destroy` using this very cool module, I get the following error:

```Error: error deleting S3 Bucket (clienta-us-east-1-audit-logs): BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.```

Given you've updated to Terraform 0.12, I think (TF newbie here) you could add the `force_destroy = true` option to all the places you use the `aws_s3_bucket` resource.

See https://github.com/terraform-providers/terraform-provider-aws/issues/208

**Comment by nozaq** [comment]
@kylelundstedt 
Thanks for the report. I added `audit_log_bucket_force_destroy` as a module input variable which then passed to `aws_s3_bucket` resources. The default value is set to `false` to prevent accidental deletion of audit log records.

**Comment by kylelundstedt** [comment]
Fantastic!!!  Thanks so much for successfully tackling this issue so quickly.

**Comment by kylelundstedt** [comment]
Hi @nozaq 

I had a new issue pop up that may (or may not) be related to the the "force destroy" option that you put in place for the audit bucket.

Now when I run the `secure-baseline` module, everything works except for the bucket-related tasks.  I get the following error after running `terragrunt apply`:

```
Error: Error creating S3 bucket: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'
        status code: 400, request id: EF33E2B670A47024, host id: QV0D2p0NuiJ8cuELIyKcJVyu7d19WLO1SNe+IbEBCa8VcVTB1Yxbb9yDGwlj6jEHwljzA6onKmc=
```

I'm passing in `region = "us-east-1"` as one of the inputs in my terragrunt.hcl file.  These inputs seem to work fine when used as part of the sub-modules like `vpc-baseline`; for example, the Default VPC gets changed correctly in each region.  However, it appears that any sub-module that depends on creating an S3 bucket (i.e., `secure-bucket`) - about 45 of the 251 actions - does not work.  Any ideas?
