### ISSUE TITLE
Feature suggestion: disable unused Regions

### ISSUE THREAD

**Issue by kylelundstedt** [nozaq/terraform-aws-secure-baseline#64]
Hi @nozaq 

Thanks again for putting me on the right track with my S3 bucket issue.

This TF module really does a nice job at securing an AWS account.  It just occurred to me that it might be nice if your users could specify a list of AWS Regions to disable (or, alternatively, a shorter list of AWS Regions that they want to use).

I think you could add such a feature to your IAM submodule, ala the following:
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws-enable-disable-regions.html

So, rather than having to enable all the protective measures herein for EVERY region, you could start by disabling any unused Regions, and simplify the process.  Just a thought.  Thanks again for all your hard work!

**Comment by nozaq** [comment]
@kylelundstedt 
Thanks for the suggestion! 
I agree that disabling regions is useful for hardening your account, and working with such situation would be really nice feature to have in this module.

I'll give it a try :)

**Comment by nozaq** [comment]
@kylelundstedt 
I've added `target_regions` argument in v0.16.0. With this argument you can specify regions you'd like to configure with this module. 
The example is [here](https://github.com/nozaq/terraform-aws-secure-baseline/tree/master/examples/select-region), please check if you have chance!
