### ISSUE TITLE
Error: Invalid index in module guardduty-baseline

### ISSUE THREAD

**Issue by DevBOFH** [nozaq/terraform-aws-secure-baseline#83]
After successfully applying the module, I'm now getting this error on future plans / applies:

Error: Invalid index

  on .terraform/modules/global.secure_baseline/nozaq-terraform-aws-secure-baseline-46c9702/modules/guardduty-baseline/outputs.tf line 3, in output "guardduty_detector":
   3:   value       = var.enabled ? aws_guardduty_detector.default[0] : null
    |----------------
    | aws_guardduty_detector.default is empty tuple

The given key does not identify an element in this collection value.

make: *** [apply] Error 1

**Comment by DevBOFH** [comment]
nevermind! was an error on my end.

**Comment by alex-benoit** [comment]
getting the same error - what was the issue?
