### ISSUE TITLE
Error: missing provider provider.aws.ap-northeast-1

### ISSUE THREAD

**Issue by sagivle** [nozaq/terraform-aws-secure-baseline#90]
Error: missing provider provider.aws.ap-northeast-1 
terraform 12.20

provider "aws" {
  version = "=2.47.0"
data "aws_caller_identity" "current" {
}

data "aws_region" "current" {
}

module "secure-baseline" {
  source  = "nozaq/secure-baseline/aws"
  version = "0.17.0"
  audit_log_bucket_name           = "audit-log-pipelines-cloud-${var.environment}"
  aws_account_id                  = data.aws_caller_identity.current.account_id
  region                          = data.aws_region.current.name
  support_iam_role_principal_arns = ["ccc@ddd.com"]
  target_regions = data.aws_region.current.name

  providers = {
    aws                = aws
    aws.ap-northeast-1 = aws.ap-northeast-1
    aws.ap-northeast-2 = aws.ap-northeast-2
    aws.ap-south-1     = aws.ap-south-1
    aws.ap-southeast-1 = aws.ap-southeast-1
    aws.ap-southeast-2 = aws.ap-southeast-2
    aws.ca-central-1   = aws.ca-central-1
    aws.eu-central-1   = aws.eu-central-1
    aws.eu-north-1     = aws.eu-north-1
    aws.eu-west-1      = aws.eu-west-1
    aws.eu-west-2      = aws.eu-west-2
    aws.eu-west-3      = aws.eu-west-3
    aws.sa-east-1      = aws.sa-east-1
    aws.us-east-1      = aws.us-east-1
    aws.us-east-2      = aws.us-east-2
    aws.us-west-1      = aws.us-west-1
    aws.us-west-2      = aws.us-west-2
  }
}

**Comment by snayler0** [comment]
For this to work @sagivle I think you need to define an aws provider per region.

Have a look at the[ providers.tf](https://github.com/nozaq/terraform-aws-secure-baseline/blob/master/providers.tf) file for an idea of how that looks.

**Comment by php-workx** [comment]
@nozaq I ran into this issue today as well. Only by reviewing the test cases I noticed that I have to define a list of providers with aliases for each AWS region. I think it would be great if we could mention this somewhere in the documentation and almost more important is to add the [regions.tf](https://github.com/nozaq/terraform-aws-secure-baseline/blob/main/test/fixtures/simple_registry/regions.tf) to the various examples here: https://github.com/nozaq/terraform-aws-secure-baseline/tree/main/examples

What do you think?

**Comment by nozaq** [comment]
@php-workx Hi, thanks for your suggestion!
Actually this is mentioned in [Usage section](https://github.com/nozaq/terraform-aws-secure-baseline#usage) and `regions.tf` is included in all examples. But maybe we could emphasize it more as defining this number of providers is not something everyone do regularly.
