### ISSUE TITLE
How to get member accounts object?

### ISSUE THREAD

**Issue by willfarrell** [nozaq/terraform-aws-secure-baseline#93]
What is the recommended way to get the member_accounts input value?

I ask because below would be really simple to get, however, your variable doesn't allow name and arn in.
```terraform-hcl
data "aws_organizations_organization" "main" {}
output "member_accounts" {
  value = data.aws_organizations_organization.main.non_master_accounts
}
/*
Outputs:
member_accounts = [
  {
    "arn" = "arn:aws:organizations::******:account/o-********/**********"
    "email" = "account+testing@example.com"
    "id" = "*********"
    "name" = "testing"
  }
]
*/
```

**Comment by nozaq** [comment]
Probably too late, but I leave my answer anyway :pray: 

You need emails and account IDs to specify member accounts as defined below.
https://github.com/nozaq/terraform-aws-secure-baseline/blob/master/variables.tf#L23
