### ISSUE TITLE
Link is dead - Check the example  (on usage section)

### ISSUE THREAD

**Issue by dariushazimi** [nozaq/terraform-aws-secure-baseline#97]
The link to your example is not found.
See the sentence below in your main read me file. 
Check the example to understand how

Under usage

https://github.com/nozaq/terraform-aws-secure-baseline/blob/master/examples/root-example/regions.tf

**Comment by matty1979** [comment]
Link is broken on the terraform registry as well as your github.

**Comment by nozaq** [comment]
@dariushazimi Thank you for the report, and sorry for taking a while to notice it.
Just fixed in #101
